version: "3.9"

services:
  react-prod:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: react-prod
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.react.rule=Host(`localhost`)"
      - "traefik.http.services.react.loadbalancer.server.port=8080"
    networks:
      - react-network

networks:
  react-network:
    driver: bridge
